name: Java CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Deploy to github package
      env:
        GH_TOKEN: ${{secrets.ACCESS_TOKEN}}
      run: mvn deploy -s settings.xml -Dtoken=${GH_TOKEN}
  
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # v2 minimum required
      - uses: axel-op/googlejavaformat-action@v2.0.0
        with:
          args: "--skip-sorting-imports --replace"
      
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: checkstyle
        run: mvn -B checkstyle:checkstyle --file pom.xml
      - name: pmd
        run: mvn -B pmd:pmd --file pom.xml
      - name: findbugs
        run: mvn -B findbugs:findbugs --file pom.xml
        
